spring:
  application:
    name: doument-service
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600000          # можно, если пригодится
  datasource:
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: doument_service
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 9002

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true