services:

  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    image: discovery-service
    restart: unless-stopped
    ports:
      - "${DISCOVERY_SERVICE_PORT}:${DISCOVERY_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      DISCOVERY_SERVICE_PORT: "${DISCOVERY_SERVICE_PORT}"

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery
    environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
        - SPRING_CLOUD_CONFIG_FAIL_FAST=true


  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api-gateway
    restart: unless-stopped
    ports:
      - "${GATEWAY_API_PORT}:${GATEWAY_API_PORT}"
    env_file:
      - .env
    environment:
      GATEWAY_API_PORT: "${GATEWAY_API_PORT}"
      EXPIRATION: "${EXPIRATION}"
      REFRESH_EXPIRATION: "${REFRESH_EXPIRATION}"
      ONE_TIME_TOKEN_EXPIRATION: "${ONE_TIME_TOKEN_EXPIRATION}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - discovery
      - config-server

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    image: auth-service
    restart: unless-stopped
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      EXPIRATION: "${EXPIRATION}"
      REFRESH_EXPIRATION: "${REFRESH_EXPIRATION}"
      ONE_TIME_TOKEN_EXPIRATION: "${ONE_TIME_TOKEN_EXPIRATION}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - discovery
      - config-server

  doument-service:   # <-- исправил название
    build:
      context: ./doument-service   # у тебя папка с опечаткой
      dockerfile: Dockerfile
    image: doument-service
    restart: unless-stopped
    ports:
      - "${DOCUMENT_SERVICE_PORT}:${DOCUMENT_SERVICE_PORT}"
    env_file:
      - .env
    environment:
      EXPIRATION: "${EXPIRATION}"
      REFRESH_EXPIRATION: "${REFRESH_EXPIRATION}"
      ONE_TIME_TOKEN_EXPIRATION: "${ONE_TIME_TOKEN_EXPIRATION}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - discovery
      - config-server

volumes:
  db-data: