spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    registry-fetch-interval-seconds: 10

logging:
  level:
    org.springframework.web.reactive.function.client: info
    org.springframework.cloud.gateway: info