spring:
  application:
    name: api-gateway
  cloud:
    config:
      fail-fast: true
      username: ${CONFIG_SERVICE_USER:user}
      password: ${CONFIG_SERVICE_PASS:config_pass}
      retry:
        initial-interval: 5000
        max-interval: 10000
        max-attempts: 10
  config:
    import: configserver:${CONFIG_URL}
    activate:
      on-profile: dev

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL}
    registry-fetch-interval-seconds: 10

logging:
  level:
    org.springframework.web.reactive.function.client: info
    org.springframework.cloud.gateway: info