server:
  port: 8082

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/

eureka.client.registry-fetch-interval-seconds: 5
eureka.client.initial-instance-info-replication-interval-seconds: 5