server:
  port: 8761

spring:
  application:
    name: discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

eureka.client.registry-fetch-interval-seconds: 5
eureka.client.initial-instance-info-replication-interval-seconds: 5